version: '3'

services:
  database:
    image: 'postgres:14'

    volumes:
      - /data/:/var/lib/postgresql/data/

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: gamelist

    command: ["postgres", "-c", "log_statement=all"]
